### ISSUE TITLE
make kurtosis service logs return the logs generated by the nodes

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/avalanche-package#50]
> Ik for a previous version this was really useful, do you have any insight to why that might be or what I may be doing wrong? I can add a GitHub issue with steps to reproduce if not

> If the logs worked so I could view it via the CLI this would be a better UX than our current network runner. To view the logs there you need to copy and paste directory paths

AaronB was trying to use the `kurtosis service logs` and the logs weren't working. This is because the entrypoint is set to `tail -f /dev/null` as the binary requires restarts.

**Comment by mieubrisse** [comment]
@h4ck3rk3y can we fix this if, using current Kurtosis toolkit, we do:
1. start the binary
2. make the subnet change
3. stop the servcie
5. grab a files artifact of the data directory
6. restart the service with the data directory
?

**Comment by h4ck3rk3y** [comment]
@mieubrisse I am fixing this in #53 by tailing the right logs from the get go. 2 line change!
